// /legal/ai-disclosure/ — which AI systems produce the feedback, what they receive, and their limits.
// Whisper on Workers AI: cloudflare-docs src/content/workers-ai-models/whisper-large-v3-turbo.json
// ("a pre-trained model for automatic speech recognition", fetched 2026-09-24). Model choice for grading
// is config (MODELS.defaultGrader, GRADER_MODEL), so the page names the model family, not a version.
import { AI_DISCLOSURE, BRAND } from '../../shared/config'
import { PATHS } from '../routes'
import { CONTACT_LINES_EN, FILTER_EN, LAST_REVIEWED, PRACTICE_MODE } from '../site'
import type { LegalPage } from '../types'

export const AI_DISCLOSURE_PAGE: LegalPage = {
  path: PATHS.aiDisclosure,
  lang: 'en',
  title: 'AI disclosure',
  description: `How ${BRAND.en} uses AI: Claude by Anthropic writes the feedback, Whisper on Cloudflare Workers AI transcribes speech, and what their limits are.`,
  lastReviewed: LAST_REVIEWED,
  lastReviewedLabel: 'Last updated',
  draftComment:
    'DRAFT AI disclosure. The owner must review and approve it before launch (business/online/owner-setup.md). Keep it in step with worker/src/grading if the models or the screening step change.',
  intro: [{ note: AI_DISCLOSURE.en }],
  sections: [
    {
      id: 'feedback',
      heading: 'Who writes the feedback',
      blocks: [
        'Written feedback is generated by Claude, an AI model made by Anthropic. When you submit a task, we send Anthropic the text of your answer (or the transcript of your recording), the task prompt, your chosen explanation language and our instructions. Claude returns feedback in a fixed format, which we check automatically before showing it to you.',
        'If Claude finds that your text is a request we cannot help with, such as a question about an immigration application or the law, you see a fixed message that we wrote instead of feedback. It points you to a licensed immigration consultant or a lawyer.',
        FILTER_EN,
      ],
    },
    {
      id: 'speech',
      heading: 'How speech becomes text',
      blocks: [
        'For speaking tasks, your recording is transcribed by Whisper, a speech-recognition model that runs on Cloudflare Workers AI. The recording is discarded after transcription; we never store audio.',
        'Transcription can mishear words, especially with background noise or an unclear recording. The feedback is based on the transcript, so a transcription mistake can lead to a comment about an error you did not make. You can read the transcript with your feedback.',
      ],
    },
    {
      id: 'limits',
      heading: 'Limits of AI feedback',
      blocks: [
        {
          ul: [
            'AI feedback can be wrong. It may miss errors, mark correct English as a mistake, or explain something poorly.',
            'The same answer can get somewhat different feedback on different attempts.',
            "The feedback describes our own criteria. It is not based on any test's marking guide.",
            'Pronunciation and fluency are not assessed, because speaking feedback is based on a transcript.',
            'Feedback is not a score and does not predict test results.',
          ],
        },
      ],
    },
    {
      id: 'practice-mode',
      heading: 'Practising without feedback uses no AI',
      blocks: [
        `When you choose "${PRACTICE_MODE.label.en}" on a practice page, no AI is involved: nothing you write or record is sent to Anthropic, to Cloudflare Workers AI or to us. ${PRACTICE_MODE.audio.en}`,
      ],
    },
    {
      id: 'no-human-review',
      heading: 'No human review',
      blocks: [
        'No person reads your answer or checks the feedback before you see it. Afterwards, the owner may look at a small sample of answers and feedback to find and fix quality problems.',
      ],
    },
    {
      id: 'support-replies',
      heading: 'Replies to support messages',
      blocks: [
        `The owner may use Claude as an assistant to draft replies to messages sent through the support form. The owner reviews every reply and sends it. The assistant is set up never to read the practice answers stored in our database. [How we handle support messages](${PATHS.privacy}).`,
      ],
    },
    {
      id: 'not-advice',
      heading: 'Not advice',
      blocks: [
        'The AI gives feedback on English practice only. It does not give immigration, legal or other professional advice. For immigration advice, contact a licensed immigration consultant who is a member of the College of Immigration and Citizenship Consultants (CICC), or a lawyer.',
      ],
    },
    {
      id: 'your-data',
      heading: 'Your data',
      blocks: [
        `We do not use your answers to train AI models. How long we keep your answers and feedback, and who processes them, is explained in our [privacy policy](${PATHS.privacy}).`,
      ],
    },
    {
      id: 'contact',
      heading: 'Questions or problems with feedback',
      blocks: ['If feedback looks wrong or inappropriate, please tell us.', { ul: CONTACT_LINES_EN }],
    },
  ],
  related: [
    { label: 'How the feedback works', href: PATHS.helpFeedback },
    { label: 'Privacy policy', href: PATHS.privacy },
    { label: 'Terms of use', href: PATHS.terms },
  ],
}
