// Disposable-email blocklist for magic-link sign-up (memo B5). NOT exhaustive: a short list of
// widely used throwaway-inbox domains, each of which appears in the community-maintained
// disposable-email-domains/disposable-email-domains blocklist (disposable_email_blocklist.conf,
// checked 2026-09-24). New throwaway domains appear daily; Turnstile and the per-email rate limit
// remain the main abuse controls.

const DISPOSABLE_DOMAINS = new Set<string>([
  '10mail.org',
  '10minemail.com',
  '10minutemail.com',
  '10minutemail.net',
  '1secmail.com',
  '1secmail.net',
  '1secmail.org',
  '20minutemail.com',
  'anonbox.net',
  'armyspy.com',
  'byom.de',
  'cuvox.de',
  'dayrep.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'dispostable.com',
  'dropmail.me',
  'einrot.com',
  'email-temp.com',
  'emailfake.com',
  'emailnator.com',
  'emailondeck.com',
  'emltmp.com',
  'fakeinbox.com',
  'fakemail.fr',
  'fakemail.net',
  'fakemailgenerator.com',
  'fexbox.org',
  'fexpost.com',
  'fleckens.hu',
  'getairmail.com',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'harakirimail.com',
  'inboxkitten.com',
  'incognitomail.org',
  'jetable.fr.nf',
  'jetable.org',
  'jourrapide.com',
  'mail.tm',
  'mail7.io',
  'mailbox.in.ua',
  'mailcatch.com',
  'maildrop.cc',
  'mailexpire.com',
  'mailforspam.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailpoof.com',
  'mailsac.com',
  'mailtemp.info',
  'mailto.plus',
  'mintemail.com',
  'minuteinbox.com',
  'moakt.com',
  'mohmal.com',
  'mvrht.com',
  'mytemp.email',
  'nada.email',
  'pokemail.net',
  'rhyta.com',
  'sharklasers.com',
  'smailpro.com',
  'spam.la',
  'spam4.me',
  'spambox.us',
  'spamex.com',
  'spamfree24.org',
  'superrito.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempinbox.com',
  'tempmail.de',
  'tempmail.ninja',
  'tempmail.plus',
  'tempmailer.com',
  'tempmailo.com',
  'tempr.email',
  'throwawaymail.com',
  'tmails.net',
  'tmpmail.net',
  'tmpmail.org',
  'trash-mail.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.io',
  'trashmail.me',
  'trashmail.net',
  'trbvm.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
])

/** True when the address's domain, or any parent domain of it, is on the blocklist. */
export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf('@')
  if (at < 0) return false
  const labels = email.slice(at + 1).toLowerCase().split('.')
  for (let i = 0; i < labels.length - 1; i++) {
    if (DISPOSABLE_DOMAINS.has(labels.slice(i).join('.'))) return true
  }
  return false
}
